/**
 * Downloads the theme's webfonts from Google Fonts and writes a local @font-face
 * stylesheet for them.
 *
 * Up to 1.1.x Philosophy requested Libre Baskerville and Montserrat from
 * fonts.googleapis.com on every page load. That is a render-blocking request to
 * a third party on every view, it hands a visitor's IP address to Google, and
 * it is the reason the theme could never be used on a site with a strict CSP.
 *
 * Montserrat is fetched as a variable font, so nine static weights collapse into
 * one file per style.
 *
 * Usage:  node tools/build-fonts.mjs
 *
 * @package Philosophy
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname( fileURLToPath( import.meta.url ) );
const themeRoot = resolve( here, '..' );
const fontDir = join( themeRoot, 'assets/fonts' );
const cssPath = join( themeRoot, 'assets/css/fonts.css' );

// A desktop Chrome UA is what makes Google Fonts serve woff2 with unicode-range.
const USER_AGENT =
	'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const API =
	'https://fonts.googleapis.com/css2' +
	'?family=Montserrat:ital,wght@0,300..800;1,300..800' +
	'&family=Libre+Baskerville:ital,wght@0,400;0,700;1,400' +
	'&display=swap';

/** Subsets worth shipping. Cyrillic, Greek and Vietnamese are not. */
const KEEP_SUBSETS = [ 'latin', 'latin-ext' ];

const response = await fetch( API, { headers: { 'User-Agent': USER_AGENT } } );

if ( ! response.ok ) {
	console.error( `Google Fonts returned ${ response.status }` );
	process.exit( 1 );
}

const source = await response.text();

/**
 * Google Fonts labels each @font-face block with a subset comment above it.
 * Splitting on those keeps the label attached to the block it describes.
 */
const blocks = [ ...source.matchAll( /\/\* ([a-z-]+) \*\/\s*(@font-face \{[\s\S]*?\})/g ) ].map(
	( match ) => ( { subset: match[ 1 ], css: match[ 2 ] } )
);

if ( ! blocks.length ) {
	console.error( 'No @font-face blocks found in the Google Fonts response.' );
	process.exit( 1 );
}

mkdirSync( fontDir, { recursive: true } );

const seen = new Map();
const out = [];

for ( const block of blocks ) {
	if ( ! KEEP_SUBSETS.includes( block.subset ) ) {
		continue;
	}

	const url = block.css.match( /url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/ )?.[ 1 ];

	if ( ! url ) {
		continue;
	}

	const family = block.css.match( /font-family: '([^']+)'/ )?.[ 1 ] ?? 'font';
	const style = block.css.match( /font-style: ([a-z]+)/ )?.[ 1 ] ?? 'normal';
	const weight = ( block.css.match( /font-weight: ([0-9 ]+)/ )?.[ 1 ] ?? '400' ).replace( / /g, '-' );

	const slug = family.toLowerCase().replace( /[^a-z0-9]+/g, '-' );
	let name = seen.get( url );

	if ( ! name ) {
		name = `${ slug }-${ weight }-${ style }-${ block.subset }.woff2`;

		const file = await fetch( url, { headers: { 'User-Agent': USER_AGENT } } );

		if ( ! file.ok ) {
			console.error( `Failed to download ${ url }` );
			process.exit( 1 );
		}

		writeFileSync( join( fontDir, name ), Buffer.from( await file.arrayBuffer() ) );
		seen.set( url, name );
	}

	out.push(
		block.css
			.replace( /url\(https:\/\/fonts\.gstatic\.com\/[^)]+\)/, `url("../fonts/${ name }")` )
			.replace( /^@font-face \{/, `/* ${ family } — ${ block.subset } */\n@font-face {` )
	);
}

const header = `/**
 * Self-hosted webfaces for Philosophy.
 *
 * Generated by tools/build-fonts.mjs — edit that script, not this file.
 *
 * Libre Baskerville and Montserrat are both licensed under the SIL Open Font
 * License 1.1, which is GPL compatible. See readme.txt for the full credits.
 */

`;

writeFileSync( cssPath, header + out.join( '\n\n' ) + '\n' );

console.log( `Wrote ${ seen.size } font files and ${ out.length } @font-face rules.` );
